### ISSUE TITLE
Gaia Guardian V2

### ISSUE THREAD

**Issue by Fortist** [kotasc3/Botania-A-New-Dawn#1]
One of my mods is looking for botania, and Im not sure which it is at the moment.
Gonna troubleshoot it in a bit.
Probably Forbidden magic or Technomancy, and it's neither.

**Comment by Fortist** [comment]
Found the mod throwing an error, a shitty and pretty mediocre Thaumcraft Addon called Thaumic Additions. Dont worry about it, that modders a faggot anyway, removed it from my pack.

**Comment by kotasc3** [comment]
Its probably some mod checking for the mod name of botania since i changed it, they should be checking for the modid anyway

**Comment by kotasc3** [comment]
actually i didnt change the name just in case stupid mods were checking for it, odd

**Comment by Fortist** [comment]
Yeah, Im not sure myself. However, New Bug. Gaia Guard V2 doesnt teleport around, and it has no drops.

**Comment by kotasc3** [comment]
f931b362fe0788f5f2b4990e0fb7f0539b2c0747

**Comment by kotasc3** [comment]
Just pushed a new release with that fix
